# Generated by Django 4.0.6 on 2022-07-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegos',
            old_name='añodecreacion',
            new_name='anodecreacion',
        ),
    ]
