# Generated by Django 4.0.6 on 2022-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0002_rename_añodecreacion_juegos_anodecreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='anodecreacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='desarrollador',
            field=models.IntegerField(),
        ),
    ]
