# Generated by Django 4.0.6 on 2022-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_juegos', '0003_alter_juegos_anodecreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='anodecreacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='desarrollador',
            field=models.CharField(max_length=50),
        ),
    ]
